### PR TITLE
FIX: backport niworkflows utility function

### PR DESCRIPTION
**Pull request by mgxd**
https://github.com/poldracklab/fmriprep/pull/2115#issuecomment-622550772

### CODE REVIEW

**Comment by oesteban** [comment]
Wouldn't this backport pertain to niworkflows?

**Comment by mgxd** [comment]
We could go about it either way? This seems like the easier route IMO, and should be replaced once we go bump to `1.3.0`

**Comment by oesteban** [comment]
I believe this function is also used in smriprep and I think that we will need to also backport there if we want to be able to progress after 0.5.2 in the 0.5.x series.

**Comment by mgxd** [comment]
shouldn't be necessary as smriprep 0.5.x series is pinned to niworkflows 1.1.x. (all these different versions are making our dependency matrix more complex than necessary, which led to this proposal in https://github.com/poldracklab/fmriprep/issues/2054#issuecomment-623509494)

**Comment by mgxd** [comment]
closing and releasing from the `maint/1.2.x` branch.

no need to include this in master.

**Pull request closed without merging**
