### PR TITLE
FIX: WM mask selection from dseg before generating report

### LINKED ISSUE #99: Unwarping report: use BIDS-Derivatives-compatible label for WM
As a result of addressing poldracklab/smriprep#176, these two lines:

https://github.com/nipreps/sdcflows/blob/8f25fd22157cf0477d4d8151d158850737f09570/sdcflows/workflows/outputs.py#L59-L60

Should be updated as in poldracklab/fmriprep#2084

### PR DESCRIPTION
**Pull request by oesteban**
Following suit of poldracklab/fmriprep#2084 and inline with nipreps/niworkflows#500, this PR uses a more robust version of the extraction code.

Resolves: #99
Depends: nipreps/niworkflows#500

### CODE REVIEW

**Comment by effigies** [comment]
Does this have any impact on derivatives?

**Comment by oesteban** [comment]
Nope, only on the reports. But we may want to downstream it to 1.1.x

**Comment by effigies** [comment]
sdcflows 1.1.x? I don't think anything depends on it.

**Comment by oesteban** [comment]
fair enough - why bother 👍

**Pull request merged**
