### PR TITLE
ENH: Add optional session distinction to wrangler

### PR DESCRIPTION
**Pull request by mgxd**
In the same vein as https://github.com/nipreps/niworkflows/pull/678

### CODE REVIEW

**Comment by mgxd** [comment]
this will be needed for https://github.com/nipreps/nibabies/pull/193 - could I get a quick review?

**Review by effigies — APPROVED** [review]

**Comment by effigies** [comment]
Bumping CI to make sure things haven't broken...

**Comment by effigies** [comment]
And naturally they broke.

**Comment by mgxd** [comment]
Yeah I would guess master is broken - this is what I was trying to fix in #269

**Pull request merged**
