### PR TITLE
Remove non-alphanumeric characters from workflow names and output entities

### LINKED ISSUE #295: B0FieldIdentifier: some characters should be replaced to set workflow name to avoid crashes in graph creation
FMRIPrep version 20.1.0
Not sure if that is in fMRIPrep or SDCFlows that the workflow name is set, but I get the following error if B0FieldIdentifier contains a `-` , and this will likely occur for other characters (I have no knowledge on dot files syntax though). 

```
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 77, in main
    fmriprep_wf.write_graph(graph2use="colored", format="svg", simple_form=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 465, in write_graph
    outfname = format_dot(dotfilename, format=format)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 1404, in format_dot
    formatted_dot, _ = _run_dot(dotfilename, format_ext=format)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 1420, in _run_dot
    res = CommandLine(cmd, terminal_output="allatonce", resource_monitor=False).run()
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
    self.raise_exception(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
dot -Tsvg -o"...../workdir/fmriprep_wf/graph.svg" ".../workdir/fmriprep_wf/graph.dot"
Standard output:

Standard error:
Error: ..../workdir/fmriprep_wf/graph.dot: syntax error in line 29 near '-'
``` 

dot file contains something like `fmriprep_wf_single_subject_01_wf_fmap_preproc_wf_in_b0id-test` on the offending line.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #295.

Changes proposed:

- Use regular expressions to remove non-alphanumeric characters from the B0FieldIdentifier used in workflow names and output entities.

### CODE REVIEW

**Review by effigies — APPROVED** [review]

**Comment by mgxd** [comment]
This is causing an error upstream:

```
Traceback (most recent call last):
  File "/opt/conda/envs/nibabies/bin/nibabies", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/cli/run.py", line 61, in main
    retval = build_workflow(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/cli/workflow.py", line 76, in build_workflow
    retval['workflow'] = init_nibabies_wf(config.execution.unique_labels)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/workflows/base.py", line 146, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/workflows/base.py", line 589, in init_single_subject_wf
    wf_inputs = getattr(fmap_wf.inputs, f'in_{estimator.bids_id}')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TraitedSpec' object has no attribute 'in_auto_00000'
```

We probably want to either change `estimator.bids_id` to ensure it is cleaned, or add a new attribute to easily access the cleaned id.

**Comment by effigies** [comment]
Let's revert. We can rethink this.

**Comment by effigies** [comment]
Reverted. What if we replace all non-alphanumeric characters with underscores?

**Comment by mgxd** [comment]
Removing or replacing both sound reasonable - it's just the sanitized id needs to be available within the `FieldmapEstimation` class so we can easily index the workflow inputs.

**Pull request merged**
