### PR TITLE
Backport 2.2.0 PRs into 2.1.x branch

### PR DESCRIPTION
**Pull request by effigies**
Backports #257, #284, #287, #288, #292, #293, #299, #310.

All of these should be uncontroversial to have in a bug-fix release. The main goal is to have a recent CircleCI run before a lot of changes to ensure that we're not regressing in artifacts.

### CODE REVIEW

**Comment by effigies** [comment]
Now also backporting #270, #277, #281, #282, #313

**Comment by effigies** [comment]
Did we resolve a L/R flip in 2.2.0? Here's tmp/tests/test-fieldmap-masked.svg in [this 2.1.x PR](https://output.circle-artifacts.com/output/job/53e831bf-d511-4fbf-b8ce-1eb85bf457af/artifacts/0/tmp/tests/test-fieldmap-masked.svg) (left) and [master](https://output.circle-artifacts.com/output/job/95b804e0-5219-43aa-8db9-3db1827ab002/artifacts/0/tmp/tests/test-fieldmap-masked.svg) (right).

image

**Comment by effigies** [comment]
Guessing this happened in #278, but will need input from @oesteban to verify that this is expected. The artifacts are gone, so I can't compare that PR immediately.

**Comment by oesteban** [comment]
I believe we have tests to check we are interpreting the output of TOPUP correctly. This is probably a flip in plotting rather than correction. Unfortunately, I would need time to check this more thoroughly - but your guess about #278 is very likely to be the source of the flip.

**Comment by effigies** [comment]
No 2.1.2 release is planned.

**Pull request closed without merging**
