### PR TITLE
FIX: Create one fieldmap estimator per EPI-IntendedFor pair

### PR DESCRIPTION
**Pull request by effigies**

### CODE REVIEW

**Comment by effigies** [comment]
Currently have TOPUP running with:

```RST
Node: single_subject_CSI1_wf (fmap_preproc_wf (wf_auto_00000 (topup (fsl)
=========================================================================


 Hierarchy : fmriprep_wf.single_subject_CSI1_wf.fmap_preproc_wf.wf_auto_00000.topup
 Exec ID : topup


Original Inputs
---------------


* args : <undefined>
* config : /opt/conda/lib/python3.8/site-packages/sdcflows/data/flirtsch/b02b0.cnf
* encoding_direction : ['y', 'y', 'y', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-', 'y-']
* encoding_file : <undefined>
* environ : {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
* estmov : <undefined>
* fwhm : <undefined>
* in_file : /scratch/fmriprep_wf/single_subject_CSI1_wf/fmap_preproc_wf/wf_auto_00000/pad_blip_slices/sub-CSI1_ses-01_acq-PA_epi_idx-000_merged_padded.nii.gz
* interp : <undefined>
* max_iter : <undefined>
* minmet : <undefined>
* numprec : <undefined>
* out_base : <undefined>
* out_corrected : <undefined>
* out_field : <undefined>
* out_jac_prefix : jac
* out_logfile : <undefined>
* out_mat_prefix : xfm
* out_warp_prefix : warpfield
* output_type : NIFTI_GZ
* readout_times : [0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788, 0.0568788]
* reg_lambda : <undefined>
* regmod : <undefined>
* regrid : <undefined>
* scale : <undefined>
* splineorder : <undefined>
* ssqlambda : <undefined>
* subsamp : <undefined>
* warp_res : <undefined>
```

That's 3 EPI and 50 BOLD volumes, which is what the old behavior was.

**Comment by effigies** [comment]
TOPUP takes forever (>5 hours) with 50 volumes. @oesteban can we set the count lower than 50?

**Comment by oesteban** [comment]
I think we never used the 50 volumes, we used the average of them.

**Comment by effigies** [comment]
Ah. Cutting max_tr down to 10 volumes (3 EPI + 10 BOLD) took about 3 hours. Doesn't look like there's a way to multi-thread.

This PR is working, so I would like to merge.

----

For a new PR, if you agree:

I think we should probably expose `max_tr` as a workflow input, which would allow fMRIPrep to add a CLI option. Looking at OpenNeuro, here are the counts of volumes in _epi files (taking just the first found in a given dataset):

```
    #ds #vol
      5    2
     15    3
      3    4
      5    5
      1    6
      2   10
      2   20
```

I have not checked whether these are intended to correct to func, dwi or asl series, but in any case it looks like setting `max_tr == 5` as a default will ensure that there are at least as many BOLD volumes used as EPI volumes acquired in ~85% of use cases.

**Pull request merged**
