### PR TITLE
MNT: Use keys.openpgp.org over sks-keyservers

### PR DESCRIPTION
**Pull request by effigies**
Addresses #220 in `maint/1.3.x`.

### CODE REVIEW

**Comment by effigies** [comment]
Okay, it looks like we need to backport more CircleCI fixes than were trivial.

**Comment by mgxd** [comment]
@effigies can this be closed?

**Comment by effigies** [comment]
We'll need to fix this if we ever need another sdcflows 1.3.x release. If not, we can close.

**Comment by mgxd** [comment]
ah, this is tied to the LTS, probably a good idea to fix it up

**Pull request closed without merging**
