### PR TITLE
SDC-pepolar: topup implementation v2

### PR DESCRIPTION
**Pull request by markushs**
Ref #37

Decided to do this as a new PR as the initial comments to #76 required implementing the approach somewhat differently. 

`pepolar.py` is now modified to run fsl topup. `pepolar.py` returns a topup estimated fieldmap (in Hz) and a "magnitude" image (the unwarped epis from topup).

Next, the topup estimated fieldmap is converted to a displacement field using routines from the `sdcflows.workflows.fmap` module (`fmap_wf` + `fmap2field_wf`).

Finally, unwarping is performed using the `sdcflow_workflows.unwarp` module.

### CODE REVIEW

**Comment by markushs** [comment]
Hi @oesteban. Is there still any interest in this approach? I'm asking as it was mentioned in a SDC-issue over at fmriprep. I had the impression that you were working on an alternative, and likely improved, implementation under dmriprep. If that's the case, should I just close the draft?

**Comment by oesteban** [comment]
Hi @markushs, thanks for bringing this up. The situation, indeed, is a bit messy.

We do have a functional alternative working for dMRIPrep -> https://github.com/nipreps/dmriprep/blob/a2cd0decb21e18697bec56942ec9c6dbda7e7e1b/dmriprep/workflows/fmap/base.py

While developing that, I realized of a few issues that are holding me back in upstreaming that code on to SDCFlows (and hence, make it available to fMRIPrep):
- The need for a more sophisticated specification from BIDS as to what was the intent of the researcher for fieldmapping, when she/he designed the acquisition protocol (bids-standard/bids-specification#622). In the end, that would resolve (or alleviate) a longstanding issue for SDCFlows (#101).
- TOPUP from FSL 5 is quite unreliable and crashes with Segmentation Faults for a number of reasons (which are not undisclosed with the error). In dMRIPrep we basically patch TOPUP from FSL 6 into the overall FSL 5 installation. This solution is definitely not transparent (and probably unacceptable for fMRIPrep - opinions @effigies @mgxd ?). Therefore, any implementation of TOPUP for fMRIPrep entails upgrading FSL to v6. This is heavily problematic as Nipype itself does not cope with FSL 6 very smoothly.

I think both issues (BIDS specs and FSL 6) are the two main blockers for this. Both have workarounds, but I honestly think they are not transparent nor worth our time. But happy to be convinced on the contrary or learning of a more creative approach.

**Comment by oesteban** [comment]
We've made some progress in uniformizing the estimation API, and now we even have a base implementation for TOPUP:
https://github.com/nipreps/sdcflows/blob/797eccb072ac9687f8671c18c4f94e37949ad7b7/sdcflows/models/pepolar.py#L25-L120

I'm sure there are many edge cases we will need to account for, but the foundation is there. We even have a test running TOPUP: https://697-189292208-gh.circle-artifacts.com/0/tmp/tests/sdcflows/sub-HCP101006/figures/sub-HCP101006_desc-pepolar_fieldmap.svg

The idea is that all estimation strategies (namely, B0 fieldmaps acquired with Spiral Echo Imaging, phase-difference fieldmaps --both 2-echos and phasediff--, pepolar-AFNI, pepolar-TOPUP, end fieldmapless-SyN) produce not just a processed version of the fieldmap, also a field of B-Splines coefficients (i.e., the fieldcoeff output of TOPUP) -- please follow progress on this at #119.

This goes along with a more clear separation of estimation and correction. Estimation will generate the field and coefficients. These can be moved to the target image to be corrected, the field interpolated from the coefficients in the new space and finally, scaled by the Readout Time to generate the actual displacements field.

**Comment by oesteban** [comment]
Hi @markushs I think we should redirect these efforts towards the implementation we have on the `dev/1.4.0` branch. Please send us all the feedback you have on that branch. Also, please let me know if you want to become a maintainer of SDCFlows, so that you can more flexibly contribute and we can also assign you reviews of PRs. We'd be excited that you joined forces with the project. WDYT?

In regards this particular PR, can I close it?

**Comment by markushs** [comment]
Hi @oesteban

**Comment by markushs** [comment]
Hi @oesteban

**Comment by markushs** [comment]
Hi @oesteban 
Great that you seem to have found a better solution for this! I'll pay attention to the dev-branch from now on (no prob closing this PR). Concerning your question, I am flattered, but not sure if I can contribute with much. My python skills are getting better though (after a long and painful transition from matlab), so happy to help if there's anything I can do.

**Comment by oesteban** [comment]
> Concerning your question, I am flattered, but not sure if I can contribute with much. My python skills are getting better though (after a long and painful transition from matlab), so happy to help if there's anything I can do.

You have already contributed with much - the fact that your two PRs on this TOPUP implementation haven't made it to master doesn't mean they don't have contributed to SDCFlows overall. Your initiative has stimulated the software go forward and has given ideas to others about how to proceed to make progress.

Looking into the future, although you might not speak Python fluently today I'm sure your feedback will be very valuable on others' PRs. And that's only the start.

Please let me know if you want to be included - as I said, we'd be honored :).

Closing this for the time being.

**Pull request closed without merging**
