### PR TITLE
CI: Ensure builds are triggered weekly

### PR DESCRIPTION
**Pull request by mgxd**

### CODE REVIEW

**Comment by effigies** [comment]
Is this to keep the cache from expiring? If not, maybe we should drop cache so we're not surprised by mismatches between `master` and PRs?

**Comment by mgxd** [comment]
is there an easy way to specify a stale cache on GHA? I agree dropping the cache can be helpful (just came up in #269) but might be excessive doing it every build

**Comment by effigies** [comment]
My guess would be adding something that changes periodically to the cache name, like `${{ date.week }}` (I just made that up).

**Comment by effigies** [comment]
Well, we can worry about better cache names later. Sorry for dropping the ball on this one, which is clearly a good idea on its own.

**Pull request merged**
